import { useState } from 'react';
import { VideoFormData, formHasTextContent } from '.';
import useAiImageQueries from '../ai/useAiImageQueries';
import { AiAutoGeneratedField } from '../ai';

export default function useVideoFormParent({
  videoForm,
  textFieldsToAutoGenerate,
  imageThumbnailBase64,
}: {
  videoForm?: Partial<VideoFormData>;
  textFieldsToAutoGenerate?: AiAutoGeneratedField[];
  imageThumbnailBase64?: string;
}) {
  const [pending, setIsPending] = useState(false);
  const [updatedTitle, setUpdatedTitle] = useState('');
  const [hasTextContent, setHasTextContent] = useState(
    videoForm ? formHasTextContent(videoForm) : false,
  );

  const aiContent = useAiImageQueries(
    textFieldsToAutoGenerate,
    imageThumbnailBase64,
  );

  return {
    pending,
    setIsPending,
    updatedTitle,
    setUpdatedTitle,
    hasTextContent,
    setHasTextContent,
    aiContent,
  };
}
