'use client';

import AdminChildPage from '@/components/AdminChildPage';
import { PATH_ADMIN_PHOTO_UPLOADS } from '@/site/paths';
import { VideoFormData, generateTakenAtFields } from './form';
import VideoForm from './form/VideoForm';
import { Tags } from '@/tag';
import useVideoFormParent from './form/useVideoFormParent';
import AiButton from './ai/AiButton';
import { AiAutoGeneratedField } from './ai';
import { useMemo } from 'react';

export default function UploadPageClient({
  blobId,
  videoFormExif,
  uniqueTags,
  hasAiTextGeneration,
  textFieldsToAutoGenerate,
  imageThumbnailBase64,
  shouldStripGpsData,
}: {
  blobId?: string;
  videoFormExif: Partial<VideoFormData>;
  uniqueTags: Tags;
  hasAiTextGeneration?: boolean;
  textFieldsToAutoGenerate?: AiAutoGeneratedField[];
  imageThumbnailBase64?: string;
  shouldStripGpsData?: boolean;
}) {
  const {
    pending,
    setIsPending,
    updatedTitle,
    setUpdatedTitle,
    hasTextContent,
    setHasTextContent,
    aiContent,
  } = useVideoFormParent({
    textFieldsToAutoGenerate,
    imageThumbnailBase64,
  });

  const initialVideoForm = useMemo(
    () => ({
      ...videoFormExif,
      // Generate missing dates on client to avoid timezone issues
      ...generateTakenAtFields(videoFormExif),
    }),
    [videoFormExif],
  );

  return (
    <AdminChildPage
      backPath={PATH_ADMIN_PHOTO_UPLOADS}
      backLabel="Uploads"
      breadcrumb={pending && updatedTitle ? updatedTitle : blobId}
      breadcrumbEllipsis
      accessory={
        hasAiTextGeneration && <AiButton {...{ aiContent, shouldConfirm: hasTextContent }} />
      }
      isLoading={pending}
    >
      <VideoForm
        initialVideoForm={initialVideoForm}
        uniqueTags={uniqueTags}
        aiContent={hasAiTextGeneration ? aiContent : undefined}
        shouldStripGpsData={shouldStripGpsData}
        onTitleChange={setUpdatedTitle}
        onTextContentChange={setHasTextContent}
        onFormStatusChange={setIsPending}
      />
    </AdminChildPage>
  );
}
